### ISSUE TITLE
Moving content 

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/components-on-a-grid#2]
I'm not sure what I'm doing wrong :(  The ul is not moving to column 2 row 1?
@hellachella @jessjodoin

**Comment by JessJodoin** [comment]
Hey! 
From looking at your code there are a few things I'm noticing.

`body {
  background-color: #f2f1ed;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 12rem 5.2rem 10rem;
}`
The grid-template-rows isn't super necessary here, we can just let the browser do the work for us. You are missing the grid-gap on there, the value is in the readme.
This is also where you should add grid-template-areas

`h1 {
  grid-column: 1 / -1;
  grid-row: 2;
  z-index: 1;
  width: 10rem;
}`
The width for the icon is also different, that value is in the readme as well

`a {
  color: #fff;
  grid-column: 2;
  grid-row: 1;
  z-index: 1;
}`
The reason your nav isn't getting placed on the grid is because you're targeting the wrong element. Try moving all the grid stuff to the nav

Hopefully this helps a little 😃
